baseURL = "https://devfest2021.gdgnantes.com/"
languageCode = "en"
title = "Devfest Nantes 2021"

# Theme
theme = "devfest-theme-hugo"

# Params
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

googleAnalytics = "UA-37717223-9"

[params]
    title = "DevFest Nantes 2021"
    date = "2021-10-21 & 2021-10-22"
    description = "The DevFest, or 'Developers Festival', is a technical conference for developers. It is aimed at students, professionals or simply curious technophiles."
    images = ["/images/social-share.jpg"]
    email = "bureau@gdgnantes.com"
    keywords = "event, gdg, gde, devfest, google, programming, android, chrome, developers, web, cloud, androiddev"
    copyright = "Organized with ❤️ by GDG Nantes."
    cfpUrl = "https://conference-hall.io/public/event/Hm6qUx8nWpLGQ2uo8ZIq"
    subscriptionUrl = "https://gdgnantes.us9.list-manage.com/subscribe/post?u=b44affc3cdfd00b20bcae502c&amp;id=e0e7ceee5d"
    appleTouchIcon = "/apple-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"
    googleWebmasterKey = "BcIJYWDHoblML5DO66_b1BGBne9J_7Oq3GjC5SDCKK"

[params.logos]
    jumbo = "/images/logos/devfest_color_text_white.svg"
    header = "/images/logos/devfest_color_text_white_white.svg"
    footer = "/images/logos/devfest_color_text_gray.svg"

[menu]
#[[menu.main]]
#    identifier = "jobs"
#    name = "Jobs"
#    url = "https://jobs.devfesttoulouse.fr/"
#    weight = 200
#    external = true

[markup.goldmark.renderer]
unsafe= true

[[menu.main]]
    identifier = "cfp"
    name = "CFP"
    url = "https://conference-hall.io/public/event/Hm6qUx8nWpLGQ2uo8ZIq"
    weight = 190
    external = true

[languages]
[languages.en]
    weight = 1
    languageName = "gb"
    languageCode = "en"

[languages.fr]
    weight = 2
    languageName = "fr"
    languageCode = "fr"

[languages.fr.params]
    description = "Le DevFest, ou 'Developers Festival', est une conférence technique destinée aux développeurs. Elle s'adresse aussi bien aux étudiants, aux professionnels ou tout simplement aux curieux technophiles."

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
